name: raizes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionStrsing while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.19+24

environment:
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  animations: ^2.0.2
  video_player: ^2.4.0
  url_launcher: ^6.1.10
  # syncfusion_flutter_pdfviewer: ^20.1.56-beta # Removido temporariamente
  youtube_player_flutter: ^9.1.2

  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  # google_maps_flutter: ^2.1.5 # Removido - usando apenas imagem estática
  # map_launcher: ^2.2.2 # Removido temporariamente para build
  flutter_svg: ^1.0.3
  validatorless: ^1.2.1
  youtube_explode_dart: ^1.12.4
  flutter_html: ^3.0.0-beta.2
  safe_device: ^1.1.4

dependency_overrides:
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Marca-home.png
    - assets/images/Marca-rio-ave.png
    - assets/images/pattern1.png
    - assets/images/pattern2.png
    - assets/images/pattern3.png
    - assets/images/pattern4.png
    - assets/images/pattern5.png
    - assets/images/family.jpg
    - assets/images/city.jpg
    - assets/images/tempo.jpg
    - assets/images/seguranca_e_conforto.png
    - assets/images/sustentabilidade.png
    - assets/images/tecnologia.png
    - assets/3.0x/Localizacao.jpg
    - assets/images/icones/
    - assets/images/plantas/GERAL/
    - assets/images/plantas/BLOCO E/
    - assets/images/plantas/BLOCO F/
    - assets/images/plantas/BLOCO G/
    - assets/images/plantas/BLOCO H/
    - assets/images/plantas/BLOCO I/
    - assets/images/areas_comuns/
    - assets/images/projetistas/Juliano Dubeux - Projeto Urbanístico/Fotos/
    - assets/images/projetistas/Metro Arquitetura - Projeto Arquitetônico/Fotos/
    - assets/images/projetistas/Sérgio Santana - Paisagista/Foto Institucional/
    - assets/images/projetistas/Zirpoli - Interiores/Fotos/
    - assets/images/areas_privativa/BLOCO E - 92m²/
    - assets/images/areas_privativa/BLOCO E - 92m² (DECORADO)/
    - assets/images/areas_privativa/BLOCO E - Cobertura Duplex/
    - assets/images/areas_privativa/BLOCO F - 48 m²/
    - assets/images/areas_privativa/BLOCO F - 56m² (DECORADO)/
    - assets/images/areas_privativa/BLOCO H - 74m²/
    - assets/misc/
    - assets/videos/
    - assets/videos/fachada-nova.tiff
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: VINILA
      fonts:
        - asset: assets/fonts/VINILA-LIGHT.otf
          weight: 300
        - asset: assets/fonts/VINILA-REGULAR.otf
          weight: 400
        - asset: assets/fonts/VINILA-BOLD-OBLIQUE.otf
          weight: 600
          style: italic
        - asset: assets/fonts/VINILA-BOLD.otf
          weight: 700
        - asset: assets/fonts/VINILA-EXTRABOLD.otf
          weight: 800
        - asset: assets/fonts/VINILA-BLACK.otf
          weight: 900
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
